version: "1.0"
info:
  model: int-scaffold
packages:
- name: TempExtProject
  gitServerName: test1
  gitUrl: https://github.com/PoojaAnandGit/TempExtProject
  gitUsername: PoojaAnandGit
  gitBranch: main
